# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eec4eeac5ca7a641ef815148ec37cefd80e671bb4dbd64a7a541336ef744a3af6443a235602868953d9bbefde4bffc4b0dfe679542c1d7e3ad656c05bdf054c9

test:
  secret_key_base: c486892012f7fcaf4210c77c322963b94563f739aeede9600d82ecc93a75bbafac971ebd2a9508d666769e226d32635c601ea875ef7f31a03860a9ab7bd5d901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
